
#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '3'
networks:
  basic:

services:
  gana:
    container_name: gana
    build: ./ganache
    ports:
      - 8545:8545
    networks:
      - basic
    volumes:
      - ./ganache/ganache-data:/var/ganache

  user:
    container_name: user
    build: .
    tty: true
    command: sh
    volumes:
      - .:/app
    ports:
      - 4000:4000
    networks:
      - basic
  
  sp:
    container_name: sp
    build: .
    tty: true
    command: sh
    volumes:
      - .:/app
    ports:
      - 4001:4001
    networks:
      - basic

  tpa:
    build: .
    container_name: tpa
    tty: true
    command: sh
    volumes:
      - .:/app
    ports:
      - 4002:4002
    networks:
      - basic
  
  # nginx:
  #     container_name: nginx
  #     build: ./nginx
  #     volumes:
  #         - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     ports:
  #         - 80:80
  #     restart: always 
  #     depends_on:
  #         - user
  #     networks:
  #         - basic